// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9zGbjE6bK_nyL5eqXY97t6kPAcWAA50',
    appId: '1:394701292156:web:449722f03ae283e2e3bff9',
    messagingSenderId: '394701292156',
    projectId: 'cmsc23-slambook-baybay',
    authDomain: 'cmsc23-slambook-baybay.firebaseapp.com',
    storageBucket: 'cmsc23-slambook-baybay.appspot.com',
    measurementId: 'G-65ZFHZ0CRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVSQ51CtpgvqtOLzY4HNBBbMdniSxS27Q',
    appId: '1:394701292156:android:9cfc9bb83637437be3bff9',
    messagingSenderId: '394701292156',
    projectId: 'cmsc23-slambook-baybay',
    storageBucket: 'cmsc23-slambook-baybay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ6QupBgRoQheEkrvwAb-UKzqev-cp8aU',
    appId: '1:394701292156:ios:4cf91174490c8887e3bff9',
    messagingSenderId: '394701292156',
    projectId: 'cmsc23-slambook-baybay',
    storageBucket: 'cmsc23-slambook-baybay.appspot.com',
    iosBundleId: 'com.example.flutterAppExr4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ6QupBgRoQheEkrvwAb-UKzqev-cp8aU',
    appId: '1:394701292156:ios:4cf91174490c8887e3bff9',
    messagingSenderId: '394701292156',
    projectId: 'cmsc23-slambook-baybay',
    storageBucket: 'cmsc23-slambook-baybay.appspot.com',
    iosBundleId: 'com.example.flutterAppExr4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx9zGbjE6bK_nyL5eqXY97t6kPAcWAA50',
    appId: '1:394701292156:web:ed9529fc2a635cb9e3bff9',
    messagingSenderId: '394701292156',
    projectId: 'cmsc23-slambook-baybay',
    authDomain: 'cmsc23-slambook-baybay.firebaseapp.com',
    storageBucket: 'cmsc23-slambook-baybay.appspot.com',
    measurementId: 'G-CE8E91LTW6',
  );

}